language: go
go:
- "1.12.3"

notifications:
  email: false

env:
- GO111MODULE=on

install:
- go mod download
- go mod verify

script:
- go test ./...

before_deploy:
- GIT_TAG=$TRAVIS_TAG make clean build

deploy:
- provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true